name: Action di Casaro
on:
  push:
jobs:
  Ciao:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ciao"
      - run: echo "Ciao 2"
      - run: ifconfig
      - run: pip --version
      - run: lsb_release -d
      - run: ls -la
      - run: pwd
      - run: env
      - uses: actions/checkout@v4
        with:
          sparse-checkout:
            casaro
      - run: ls -la
  